[[group]]
name = "test2"
description = "test group 2"
command = ""

    [[group.entry]]
    name = "ls ~/.config"
    name_is_command = true
    command = 'open -a "{name}"'

    [[group.entry]]
    name = "Test"
    name_is_command = false
    command = 'echo Test'

    [group.input_field]
    name = "Search for an application"
    display_text = "Search for an application"
    action = "fuzzy search"
    command = 'open -a "{input}"'
